# Generated by Django 4.0.4 on 2022-07-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_code', models.IntegerField(blank=True, max_length=3, null=True)),
                ('mobile', models.IntegerField(max_length=15, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_registration.position')),
            ],
        ),
    ]
