# Generated by Django 4.0.4 on 2022-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
